# Generated by Django 5.0.3 on 2024-03-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstbl',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
