# Generated by Django 5.0.3 on 2024-03-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
